# Generated by Django 5.2.6 on 2026-01-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avg_hold_time_ms', models.FloatField(blank=True, null=True)),
                ('avg_flight_time_ms', models.FloatField(blank=True, null=True)),
                ('hold_variability_ms', models.FloatField(blank=True, null=True)),
                ('flight_variability_ms', models.FloatField(blank=True, null=True)),
                ('effort_score', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_results', to='DisabilityDetectApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_fixations', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_fixation_duration_ms', models.FloatField(blank=True, null=True)),
                ('avg_saccade_length_px', models.FloatField(blank=True, null=True)),
                ('regression_rate_percent', models.FloatField(blank=True, null=True)),
                ('signals_detected', models.TextField(blank=True)),
                ('raw_gaze_data', models.JSONField(blank=True, default=dict, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='DisabilityDetectApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='RVPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_digits', models.PositiveIntegerField(blank=True, null=True)),
                ('hits', models.PositiveIntegerField(blank=True, null=True)),
                ('misses', models.PositiveIntegerField(blank=True, null=True)),
                ('false_alarms', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('sensitivity_aprime', models.FloatField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvp_results', to='DisabilityDetectApp.user')),
            ],
        ),
    ]
