# Generated by Django 5.2.6 on 2026-01-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabilityDetectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hits', models.PositiveIntegerField()),
                ('omissions', models.PositiveIntegerField()),
                ('commissions', models.PositiveIntegerField()),
                ('avg_reaction_time_ms', models.FloatField()),
                ('total_trials', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_results', to='DisabilityDetectApp.user')),
            ],
        ),
    ]
