# Generated by Django 5.2.6 on 2026-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabilityDetectApp', '0002_attentionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionresult',
            name='targets_shown',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
