# Generated by Django 5.2.6 on 2026-01-17 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabilityDetectApp', '0003_attentionresult_targets_shown'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutismResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('signals', models.CharField(blank=True, max_length=50, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DisabilityDetectApp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='RVPResult',
        ),
    ]
