# Generated by Django 5.2.6 on 2026-01-17 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabilityDetectApp', '0004_autismresult_delete_rvpresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyscalculiaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('accuracy_percent', models.FloatField()),
                ('avg_response_time_ms', models.FloatField()),
                ('number_reversal_detected', models.BooleanField(default=False)),
                ('signals_detected', models.TextField(blank=True)),
                ('summary_text', models.TextField()),
                ('raw_responses', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyscalculia_results', to='DisabilityDetectApp.user')),
            ],
        ),
    ]
