# Generated by Django 5.2.6 on 2026-01-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisabilityDetectApp', '0005_dyscalculiaresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyscalculiaresult',
            name='avg_typing_time_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dyscalculiaresult',
            name='total_time_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dyscalculiaresult',
            name='total_typing_time_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dyscalculiaresult',
            name='typing_cpm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dyscalculiaresult',
            name='typing_wpm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dyscalculiaresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisabilityDetectApp.user'),
        ),
    ]
