"""
Django settings for DisabilityDetectProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# In settings.py (add this near the top if not already using environ)
import os
import dj_database_url

# ... other imports ...

# Define BASE_DIR here (add if missing)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ...

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600,           # optional: keep connections alive longer
        conn_health_checks=True,    # optional: Django 4.2+
    )
}

from pathlib import Path
import os
BASE_DIR = Path(__file__).resolve().parent.parent

# Then in default:
default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g&#_4$v-!=@hi9fg5ii_^hrv9pcz80f5ih)&9wtnhy53nbkjsh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your app
    'DisabilityDetectApp',

    # Optional / future common additions
    # 'django.contrib.sites',               # if using sites framework or allauth
    # 'django_extensions',                  # very useful in development
    # 'debug_toolbar',                      # only add in development settings
    # 'rest_framework',                     # if you add API endpoints
    # 'corsheaders',                        # if frontend is separate (e.g. React/Vue)
    # 'crispy_forms',                       # nicer form rendering
    # 'crispy_bootstrap5',                  # bootstrap 5 integration with crispy
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DisabilityDetectProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DisabilityDetectProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from decouple import config

GROQ_API_KEY = config('GROQ_API_KEY')

DEBUG = False
ALLOWED_HOSTS = ['*']                   # temporary – tighten later
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',      # MUST be before auth
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',   # MUST be after sessions
    'django.contrib.messages.middleware.MessageMiddleware',      # MUST be after auth
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add these for production (if deploying soon):
    #'whitenoise.middleware.WhiteNoiseMiddleware',  # ← add near top if using WhiteNoise
]

# WhiteNoise settings (optional but recommended)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Database — use Railway PostgreSQL (we'll set DATABASE_URL later)
# Remove or comment out the sqlite3 part for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}   # ← Railway will override this with env var

# Security (good practice)
SECURE_SSL_REDIRECT = True          # Railway provides HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True